networks:
  bthloggen:

services:
  server:
    image: log-server                                                                   # DEV
    container_name: "log-server"
    networks:
      - bthloggen
    restart:
      "always"
    ports:
      - "8080:8000"                                                                     # DEV
    volumes:
      - ./data:/server/app/data
      - ./server/app/src/log_handler.py:/server/app/src/log_handler.py                  # DEV
      - ./server/app/main.py:/server/app/main.py                                        # DEV
    command: ["fastapi", "dev", "app/main.py", "--host", "0.0.0.0", "--port", "8000"]   # DEV

  client:
    image: log-client                                                                   # DEV
    container_name: "log-client"
    networks:
      - bthloggen
    links:
      - server:log-server
    volumes:
      - ./client/bthloggen.bash:/client/bthloggen.bash                                  # DEV
      - ./client/src:/client/src                                                        # DEV

  webbclient:
    # build: ./webbclient
    image: log-webclient
    container_name: log-webclient
    networks:
      - bthloggen
    restart:
      "always"
    links:
      - server:log-server
    ports:
      - 1338:3000
    # develop:
    #   watch:
    #     - action: sync
    #       path: ./webbclient/public
    #       target: /webclient/public
    #     - action: sync
    #       path: ./webbclient/views
    #       target: /webclient/views
    #     - action: sync+restart
    #       path: ./webbclient/routes
    #       target: /webclient/routes
    volumes:                                                                            # DEV
      - ./webbclient/public:/webclient/public
      - ./webbclient/views:/webclient/views
      - ./webbclient/routes:/webclient/routes
      - ./webbclient/models:/webclient/models
