networks:
  bthloggen:

services:
  server:
    image: lohengrin1337/bthloggen-server:1.0
    container_name: "log-server"
    networks:
      - bthloggen
    restart:
      "always"
    ports:
      - "8080:8000"
    volumes:
      - ./data:/server/app/data

  client:
    image: lohengrin1337/bthloggen-client:1.0
    container_name: "log-client"
    networks:
      - bthloggen
    links:
      - server:log-server

  webbclient:
    image: lohengrin1337/bthloggen-webbclient:1.0
    container_name: log-webclient
    networks:
      - bthloggen
    restart:
      "always"
    links:
      - server:log-server
    ports:
      - 1338:3000
