networks:
    maze-network:

services:
    server:
        image: lohengrin1337/vlinux-mazeserver:1.0
        container_name: "maze-server"
        networks:
            maze-network:
        restart:
            "always"

    client:
        image: lohengrin1337/vlinux-mazeclient:loop
        container_name: "maze-client"
        networks:
            maze-network:
        links:
           - server:maze-server


# filename should rather be 'compose.yaml'
